# Generated by Django 3.2.8 on 2022-01-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20220129_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
