# Generated by Django 3.2.8 on 2022-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_reguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUserDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(max_length=6)),
                ('usertype', models.CharField(choices=[('Doc', 'Doctor'), ('Patients', 'Patients')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
