# Generated by Django 3.2.8 on 2022-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20220129_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguserdet',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
