# Generated by Django 3.2.8 on 2022-01-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20220130_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegUserDet',
            new_name='UserDetNew',
        ),
    ]
