# Generated by Django 3.2.8 on 2022-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_rename_reguserdet_userdetnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetnew',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
