# Generated by Django 3.2.8 on 2022-01-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_userdetnew_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetnew',
            name='profile_pic',
            field=models.ImageField(default='T', upload_to=''),
        ),
    ]
