# Generated by Django 3.2.8 on 2022-01-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_userdetnew_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetnew',
            name='profile_pic',
            field=models.ImageField(upload_to='uploads/pimg/'),
        ),
    ]
