# Generated by Django 3.1.5 on 2022-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_userdetnew_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetnew',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
